In [20]:
import pandas as pd
import numpy as np

## Hall of Fame List

In [21]:
hof_data = pd.read_csv('data/HOF_data.csv')

In [22]:
def qb_and_rb(pos):
    if pos == 'QB':
        return pos
    else:
        return np.nan

In [23]:
hof_data['Pos'] = hof_data['Pos'].apply(lambda x: qb_and_rb(x))
hof_data.drop('Lng.2', axis=1, inplace=True)
hof_data.drop('Lng.1', axis=1, inplace=True)
hof_data.drop('TD.2', axis=1, inplace=True)
hof_data.drop('Yds.3', axis=1, inplace=True)
hof_data.drop('Yds.1', axis=1, inplace=True)
hof_data.drop('Rec', axis=1, inplace=True)
hof_data.drop('CarAV', axis=1, inplace=True)
hof_data.drop('St', axis=1, inplace=True)
hof_data.drop('Lng', axis=1, inplace=True)

In [24]:
hof_data.dropna(inplace=True)
hof_data.reset_index(inplace=True)
hof_data.drop('index', axis=1, inplace=True)

In [25]:
hof_data.rename(columns={'AP1': 'First_Team_AP', 'G': 'Num_Games', 'PB': 'Pro_Bowl', 'Cmp': 'Pass_Cmp', 'Att': 'Pass_Att', 'Yds': 'Pass_Yds'}, inplace=True)
hof_data.rename(columns={'TD': 'Pass_TD', 'Int': 'Interceptions', 'Sk': 'Times_Sacked', 'Att.1': 'Rushing_Att', 'Yds.2': 'Rushing_Yds', 'TD.1': 'Rushing_Tds',}, inplace=True)

In [26]:
hof_data

,Rk,Player,Pos,Indct,From,To,First_Team_AP,Pro_Bowl,Num_Games,Pass_Cmp,Pass_Att,Pass_Yds,Pass_TD,Interceptions,Times_Sacked,Rushing_Att,Rushing_Yds,Rushing_Tds
0,19,Kurt Warner\WarnKu00,QB,2017,1998,2009,2,4,124,2666.0,4070.0,32344.0,208.0,128.0,260.0,173.0,286.0,3.0
1,20,Brett Favre\FavrBr00,QB,2016,1991,2010,3,11,302,6300.0,10169.0,71838.0,508.0,336.0,525.0,602.0,1844.0,14.0
2,24,Ken Stabler\StabKe00,QB,2016,1970,1984,1,4,184,2270.0,3793.0,27938.0,194.0,222.0,281.0,118.0,93.0,4.0
3,81,Troy Aikman\AikmTr00,QB,2006,1989,2000,0,6,165,2898.0,4715.0,32942.0,165.0,141.0,259.0,327.0,1016.0,9.0
4,83,Warren Moon\MoonWa00,QB,2006,1984,2000,0,9,208,3988.0,6823.0,49325.0,291.0,233.0,458.0,543.0,1736.0,22.0
5,87,Dan Marino\MariDa00,QB,2005,1983,1999,3,9,242,4967.0,8358.0,61361.0,420.0,252.0,270.0,301.0,87.0,9.0
6,89,Steve Young\YounSt00,QB,2005,1985,1999,3,7,169,2667.0,4149.0,33124.0,232.0,107.0,358.0,722.0,4239.0,43.0
7,92,John Elway\ElwaJo00,QB,2004,1983,1998,0,9,234,4123.0,7250.0,51475.0,300.0,226.0,516.0,774.0,3407.0,33.0
8,100,Jim Kelly\KellJi00,QB,2002,1986,1996,1,5,160,2874.0,4779.0,35467.0,237.0,175.0,323.0,304.0,1049.0,7.0
9,110,Joe Montana\MontJo01,QB,2000,1979,1994,3,8,192,3409.0,5391.0,40551.0,273.0,139.0,313.0,457.0,1676.0,20.0
10,137,Dan Fouts\FoutDa00,QB,1993,1973,1987,2,6,181,3297.0,5604.0,43040.0,254.0,242.0,319.0,224.0,476.0,13.0
11,148,Bob Griese\GrieBo00,QB,1990,1967,1980,2,8,161,1926.0,3429.0,25092.0,192.0,172.0,267.0,261.0,994.0,7.0
12,154,Terry Bradshaw\BradTe00,QB,1989,1970,1983,1,3,168,2025.0,3901.0,27989.0,212.0,210.0,307.0,444.0,2257.0,32.0
13,162,Len Dawson\DawsLe00,QB,1987,1957,1975,2,7,211,2136.0,3741.0,28711.0,239.0,183.0,167.0,294.0,1293.0,9.0
14,171,Fran Tarkenton\TarkFr00,QB,1986,1961,1978,1,9,246,3686.0,6467.0,47003.0,342.0,266.0,274.0,675.0,3674.0,32.0
15,174,Joe Namath\NamaJo00,QB,1985,1965,1977,1,5,140,1886.0,3762.0,27663.0,173.0,220.0,109.0,71.0,140.0,7.0
16,176,Roger Staubach\StauRo00,QB,1985,1969,1979,0,6,131,1685.0,2958.0,22700.0,153.0,109.0,313.0,410.0,2264.0,20.0
17,182,Sonny Jurgensen\JurgSo00,QB,1983,1957,1974,2,5,218,2433.0,4262.0,32224.0,255.0,189.0,94.0,181.0,493.0,15.0
18,190,George Blanda\BlanGe00,QB,1981,1949,1975,1,4,340,1911.0,4007.0,26920.0,236.0,277.0,12.0,135.0,344.0,9.0
19,200,Johnny Unitas\UnitJo00,QB,1979,1956,1973,5,10,211,2830.0,5186.0,40239.0,290.0,253.0,74.0,450.0,1777.0,13.0
20,208,Bart Starr\StarBa00,QB,1977,1956,1971,1,4,196,1808.0,3149.0,24718.0,152.0,138.0,59.0,247.0,1308.0,15.0

## Basic Stats and Player ID Look Up for Other Tables

In [27]:
basic_stats = pd.read_csv('data/Basic_Stats.csv')

In [28]:
basic_stats = pd.read_csv('data/Basic_Stats.csv')
basic_stats.drop('Position', axis=1, inplace=True)
basic_stats.drop('Number', axis=1, inplace=True)
basic_stats.drop('Current Team', axis=1, inplace=True)
basic_stats.drop('High School', axis=1, inplace=True)
basic_stats.drop('Age', axis=1, inplace=True)
basic_stats.drop('High School Location', axis=1, inplace=True)
#basic_stats.dropna(inplace=True)
basic_stats.reset_index(inplace=True)
basic_stats.drop('index', axis=1, inplace=True)
basic_stats.rename(columns={'Player Id': 'Player_Id'}, inplace=True)
basic_stats.head()

,Birth Place,Birthday,College,Current Status,Experience,Height (inches),Name,Player_Id,Weight (lbs),Years Played
0,"Grand Rapids , MI",5/23/1921,Notre Dame,Retired,3 Seasons,71.0,"Evans, Fred",fredevans/2513736,185.0,1946 - 1948
1,"Dayton , OH",12/21/1930,Dayton,Retired,1 Season,70.0,"Raiff, Jim",jimraiff/2523700,235.0,1954 - 1954
2,"Temple , TX",9/11/1960,Louisiana Tech,Retired,1 Season,74.0,"Fowler, Bobby",bobbyfowler/2514295,230.0,1985 - 1985
3,"New Orleans , LA",9/30/1986,LSU,Retired,5 Seasons,73.0,"Johnson, Quinn",quinnjohnson/79593,255.0,2009 - 2013
4,"Detroit , MI",3/31/1992,Central Michigan,Active,3rd season,77.0,"Walton, L.T.",l.t.walton/2552444,305.0,NaN

## Linking Player ID From Stats Tables to HOF Table

In [29]:
player_ids = []
not_in = []
not_in_index = []
i = 0
for item in hof_data['Player']:
    name = item.split('\\')[0]
    name = name.split(' ')
    name = name[1] + ', ' + name[0]
    found = basic_stats[basic_stats['Name'].str.contains(name)]
    if name == 'Young, Steve':
        player_ids.append(found.Player_Id.to_string().split(' ')[8])
    elif name == 'Kelly, Jim':
        player_ids.append(found.Player_Id.to_string().split(' ')[10])
    else:
        check = found.Player_Id.to_string().split(' ')
        if len(check) < 5:
            print(name)
            print(i)
            not_in.append(name)
            not_in_index.append(i)
        else:
            player_ids.append(found.Player_Id.to_string().split(' ')[4])
    
    i = i + 1

Stabler, Ken
2
Moon, Warren
4
Montana, Joe
9
Griese, Bob
11
Bradshaw, Terry
12
Staubach, Roger
16
Jurgensen, Sonny
17
Blanda, George
18
Starr, Bart
20

In [30]:
hof_data_with_id = hof_data.drop(2, axis=0)
hof_data_with_id.drop(4, axis=0, inplace=True)
hof_data_with_id.drop(9, axis=0, inplace=True)
hof_data_with_id.drop(11, axis=0, inplace=True)
hof_data_with_id.drop(12, axis=0, inplace=True)
hof_data_with_id.drop(16, axis=0, inplace=True)
hof_data_with_id.drop(17, axis=0, inplace=True)
hof_data_with_id.drop(18, axis=0, inplace=True)
hof_data_with_id.drop(20, axis=0, inplace=True)
hof_data_with_id.reset_index(inplace=True)
hof_data_with_id.drop('index', axis=1, inplace=True)
hof_data_with_id['Player_Id'] = player_ids

In [31]:
hof_data_with_id

,Rk,Player,Pos,Indct,From,To,First_Team_AP,Pro_Bowl,Num_Games,Pass_Cmp,Pass_Att,Pass_Yds,Pass_TD,Interceptions,Times_Sacked,Rushing_Att,Rushing_Yds,Rushing_Tds,Player_Id
0,19,Kurt Warner\WarnKu00,QB,2017,1998,2009,2,4,124,2666.0,4070.0,32344.0,208.0,128.0,260.0,173.0,286.0,3.0,kurtwarner/2503540
1,20,Brett Favre\FavrBr00,QB,2016,1991,2010,3,11,302,6300.0,10169.0,71838.0,508.0,336.0,525.0,602.0,1844.0,14.0,brettfavre/2500606
2,81,Troy Aikman\AikmTr00,QB,2006,1989,2000,0,6,165,2898.0,4715.0,32942.0,165.0,141.0,259.0,327.0,1016.0,9.0,troyaikman/2499369
3,87,Dan Marino\MariDa00,QB,2005,1983,1999,3,9,242,4967.0,8358.0,61361.0,420.0,252.0,270.0,301.0,87.0,9.0,danmarino/2501869
4,89,Steve Young\YounSt00,QB,2005,1985,1999,3,7,169,2667.0,4149.0,33124.0,232.0,107.0,358.0,722.0,4239.0,43.0,steveyoung/2503843
5,92,John Elway\ElwaJo00,QB,2004,1983,1998,0,9,234,4123.0,7250.0,51475.0,300.0,226.0,516.0,774.0,3407.0,33.0,johnelway/2500547
6,100,Jim Kelly\KellJi00,QB,2002,1986,1996,1,5,160,2874.0,4779.0,35467.0,237.0,175.0,323.0,304.0,1049.0,7.0,
7,137,Dan Fouts\FoutDa00,QB,1993,1973,1987,2,6,181,3297.0,5604.0,43040.0,254.0,242.0,319.0,224.0,476.0,13.0,danfouts/2514293
8,162,Len Dawson\DawsLe00,QB,1987,1957,1975,2,7,211,2136.0,3741.0,28711.0,239.0,183.0,167.0,294.0,1293.0,9.0,lendawson/2512662
9,171,Fran Tarkenton\TarkFr00,QB,1986,1961,1978,1,9,246,3686.0,6467.0,47003.0,342.0,266.0,274.0,675.0,3674.0,32.0,frantarkenton/2527019
10,174,Joe Namath\NamaJo00,QB,1985,1965,1977,1,5,140,1886.0,3762.0,27663.0,173.0,220.0,109.0,71.0,140.0,7.0,joenamath/2521943
11,200,Johnny Unitas\UnitJo00,QB,1979,1956,1973,5,10,211,2830.0,5186.0,40239.0,290.0,253.0,74.0,450.0,1777.0,13.0,johnnyunitas/2527792

## All Passing Data Stats

In [13]:
passing_data = pd.read_csv('data/Career_Stats_Passing.csv')

In [14]:
passing_data = pd.read_csv('data/Career_Stats_Passing.csv')
passing_data.drop('Longest Pass', axis=1, inplace=True)
passing_data.drop('Position', axis=1, inplace=True)
passing_data = passing_data.replace('--',np.nan)
passing_data['Passer Rating'] = passing_data['Passer Rating'].apply(lambda x: np.nan if x == 0 else x)
passing_data.dropna(inplace=True)
passing_data.reset_index(inplace=True)
passing_data.drop('index', axis=1, inplace=True)
passing_data.head()

,Player Id,Name,Year,Team,Games Played,Passes Attempted,Passes Completed,Completion Percentage,Pass Attempts Per Game,Passing Yards,...,Passing Yards Per Game,TD Passes,Percentage of TDs per Attempts,Ints,Int Rate,Passes Longer than 20 Yards,Passes Longer than 40 Yards,Sacks,Sacked Yards Lost,Passer Rating
0,tomfarris/2513861,"Farris, Tom",1947,Chicago Bears,9,2,0,0.0,0.2,0,...,0.0,0,0.0,0,0.0,0,0,0,0,39.6
1,tomfarris/2513861,"Farris, Tom",1946,Chicago Bears,11,21,8,38.1,1.9,108,...,9.8,1,4.8,2,9.5,0,0,0,0,31.5
2,billdemory/2512778,"Demory, Bill",1973,New York Jets,6,39,12,30.8,6.5,159,...,26.5,2,5.1,8,20.5,0,0,8,73,22.2
3,breezyreid/2523928,"Reid, Breezy",1951,Green Bay Packers,12,1,0,0.0,0.1,0,...,0.0,0,0.0,0,0.0,0,0,0,0,39.6
4,johnnyknolla/2518652,"Knolla, Johnny",1945,Chicago Cardinals,7,1,0,0.0,0.1,0,...,0.0,0,0.0,0,0.0,0,0,0,0,39.6

## All Quarterback Stats

In [15]:
qb = pd.read_csv('data/Game_Logs_Quarterback.csv')

In [16]:
# win marked by 1 loss is 0
# home makred by 1 away marked by 0

In [17]:
qb.drop('Position', axis=1, inplace=True)
qb.drop('Game Date', axis=1, inplace=True)
qb.drop('Games Played', axis=1, inplace=True)
qb.drop('Games Started', axis=1, inplace=True)
qb['Season'] = qb['Season'].apply(lambda x: np.nan if x == 'Preseason' else x)
qb['Home or Away'] = qb['Home or Away'].apply(lambda x: 0 if x == 'Away' else 1)
qb.rename(columns={'Home or Away': 'Home'}, inplace=True)
qb = qb.replace('--',np.nan)
qb.dropna(inplace=True)
qb.drop('Season', axis=1, inplace=True)
qb['Outcome'] = qb['Outcome'].apply(lambda x: 0 if x == 'L' else 1)
qb.reset_index(inplace=True)
qb.drop('index', axis=1, inplace=True)
qb

,Player Id,Name,Year,Week,Home,Opponent,Outcome,Score,Passes Completed,Passes Attempted,...,Ints,Sacks,Sacked Yards Lost,Passer Rating,Rushing Attempts,Rushing Yards,Yards Per Carry,Rushing TDs,Fumbles,Fumbles Lost
0,tomsavage/2543640,"Savage, Tom",2016,17,0,TEN,0,17 to 24,5,8,...,0,1,15,67.2,2,1,0.5,0,1,1
1,tomsavage/2543640,"Savage, Tom",2014,15,0,IND,0,10 to 17,10,19,...,1,1,5,51.9,4,-4,-1.0,0,2,1
2,tommymaddox/2501842,"Maddox, Tommy",2005,6,1,JAC,0,17 to 23,11,28,...,3,2,9,30.1,3,15,5.0,0,1,1
3,tommymaddox/2501842,"Maddox, Tommy",2005,11,0,BAL,0,13 to 16,19,36,...,1,6,34,70.4,4,11,2.8,0,1,1
4,tommymaddox/2501842,"Maddox, Tommy",2004,1,1,OAK,1,24 to 21,13,22,...,0,2,12,78.2,3,13,4.3,0,2,1
5,tommymaddox/2501842,"Maddox, Tommy",2004,2,0,BAL,0,13 to 30,4,13,...,0,2,10,49.2,1,1,1.0,0,1,1
6,tommymaddox/2501842,"Maddox, Tommy",2003,4,1,TEN,0,13 to 30,31,47,...,2,3,25,68.8,2,-1,-0.5,0,1,0
7,tommymaddox/2501842,"Maddox, Tommy",2002,9,0,CLE,1,23 to 20,23,42,...,1,2,10,77.4,3,8,2.7,0,2,0
8,tommymaddox/2501842,"Maddox, Tommy",2002,10,1,ATL,1,34 to 34,28,41,...,1,2,10,129.4,2,7,3.5,0,1,1
9,tommymaddox/2501842,"Maddox, Tommy",2002,14,1,HOU,0,6 to 24,30,57,...,2,6,32,55.1,2,6,3.0,0,1,1
10,tommymaddox/2501842,"Maddox, Tommy",2002,15,1,CAR,1,30 to 14,20,33,...,1,2,12,76.5,1,0,0.0,0,2,0
11,tommymaddox/2501842,"Maddox, Tommy",2001,17,1,CLE,1,28 to 7,6,8,...,1,1,4,115.1,1,8,8.0,0,1,0
12,tommymaddox/2501842,"Maddox, Tommy",1993,19,0,RAI,0,24 to 42,3,7,...,0,0,0,58.0,1,1,1.0,0,1,0
13,tommymaddox/2501842,"Maddox, Tommy",1992,12,0,RAI,0,0 to 24,18,26,...,2,4,25,60.9,1,1,1.0,0,3,1
14,tommymaddox/2501842,"Maddox, Tommy",1992,14,1,DAL,0,27 to 31,10,17,...,4,2,14,76.6,2,2,1.0,0,1,1
15,teemartin/2504246,"Martin, Tee",2003,16,1,GB,0,7 to 41,4,5,...,0,1,5,112.5,1,6,6.0,0,1,1
16,teemartin/2504246,"Martin, Tee",2003,17,0,SD,0,14 to 21,2,11,...,1,0,0,1.7,4,22,5.5,0,2,0
17,davidgarrard/2505101,"Garrard, David",2010,3,1,PHI,0,3 to 28,13,30,...,1,7,53,38.9,7,32,4.6,0,1,0
18,davidgarrard/2505101,"Garrard, David",2010,5,0,BUF,1,36 to 26,16,20,...,1,2,13,122.5,3,9,3.0,0,1,1
19,davidgarrard/2505101,"Garrard, David",2010,8,0,DAL,1,35 to 17,17,21,...,0,3,22,157.8,2,2,1.0,1,1,1
20,davidgarrard/2505101,"Garrard, David",2010,11,1,CLE,1,24 to 20,20,34,...,3,4,28,65.1,3,9,3.0,0,1,1
21,davidgarrard/2505101,"Garrard, David",2010,12,0,NYG,0,20 to 24,20,35,...,1,4,41,57.1,6,41,6.8,1,3,1
22,davidgarrard/2505101,"Garrard, David",2010,15,0,IND,0,24 to 34,24,38,...,1,1,5,93.5,4,8,2.0,0,2,0
23,davidgarrard/2505101,"Garrard, David",2010,16,1,WAS,0,17 to 20,22,38,...,2,4,41,70.0,6,39,6.5,1,2,0
24,davidgarrard/2505101,"Garrard, David",2009,2,1,ARI,0,17 to 31,23,43,...,1,4,7,79.8,4,27,6.8,0,3,1
25,davidgarrard/2505101,"Garrard, David",2009,4,1,TEN,1,37 to 17,27,37,...,0,2,18,126.3,8,38,4.8,0,1,1
26,davidgarrard/2505101,"Garrard, David",2009,5,0,SEA,0,0 to 41,18,31,...,0,4,26,75.7,1,1,1.0,0,2,2
27,davidgarrard/2505101,"Garrard, David",2009,8,0,TEN,0,13 to 30,14,27,...,2,3,22,35.9,3,22,7.3,0,1,0
28,davidgarrard/2505101,"Garrard, David",2009,10,0,NYJ,1,24 to 22,16,26,...,0,2,13,101.6,6,11,1.8,1,1,1
29,davidgarrard/2505101,"Garrard, David",2009,11,1,BUF,1,18 to 15,21,30,...,1,2,7,87.5,6,16,2.7,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3522,aaronrodgers/2506363,"Rodgers, Aaron",2009,12,0,DET,1,34 to 12,28,39,...,0,1,6,124.7,1,5,5.0,0,1,1
3523,aaronrodgers/2506363,"Rodgers, Aaron",2009,14,0,CHI,1,21 to 14,16,24,...,0,3,23,88.9,3,6,2.0,0,1,1
3524,aaronrodgers/2506363,"Rodgers, Aaron",2009,16,1,SEA,1,48 to 10,12,23,...,0,1,9,103.0,1,9,9.0,0,1,0
3525,aaronrodgers/2506363,"Rodgers, Aaron",2009,18,0,ARI,0,45 to 51,28,42,...,1,5,19,121.4,3,13,4.3,1,1,1
3526,aaronrodgers/2506363,"Rodgers, Aaron",2008,1,1,MIN,1,24 to 19,18,22,...,0,0,0,115.5,8,35,4.4,1,1,0
3527,aaronrodgers/2506363,"Rodgers, Aaron",2008,2,0,DET,1,48 to 25,24,38,...,0,1,4,117.0,4,25,6.3,0,2,1
3528,aaronrodgers/2506363,"Rodgers, Aaron",2008,3,1,DAL,0,16 to 27,22,39,...,0,5,40,80.1,5,10,2.0,1,1,0
3529,aaronrodgers/2506363,"Rodgers, Aaron",2008,6,0,SEA,1,27 to 17,21,30,...,0,2,8,111.5,6,23,3.8,1,1,1
3530,aaronrodgers/2506363,"Rodgers, Aaron",2008,9,0,TEN,0,16 to 19,22,41,...,1,4,26,76.7,2,11,5.5,0,1,1
3531,aaronrodgers/2506363,"Rodgers, Aaron",2008,10,0,MIN,0,27 to 28,15,26,...,0,4,32,72.9,1,1,1.0,0,1,0
3532,aaronrodgers/2506363,"Rodgers, Aaron",2008,12,0,NO,0,29 to 51,23,41,...,3,2,14,59.8,8,36,4.5,1,1,0
3533,aaronrodgers/2506363,"Rodgers, Aaron",2008,15,0,JAC,0,16 to 20,20,32,...,1,3,24,87.8,5,22,4.4,0,1,0
3534,aaronrodgers/2506363,"Rodgers, Aaron",2008,17,1,DET,1,31 to 21,21,31,...,0,4,35,132.2,1,-1,-1.0,0,1,0
3535,aaronrodgers/2506363,"Rodgers, Aaron",2006,11,1,NE,0,0 to 35,4,12,...,0,3,18,42.4,2,11,5.5,0,1,1
3536,aaronrodgers/2506363,"Rodgers, Aaron",2005,15,0,BAL,0,3 to 48,8,15,...,1,3,28,36.8,1,8,8.0,0,2,2
3537,chrisweinke/2504686,"Weinke, Chris",2006,14,1,NYG,0,13 to 27,34,61,...,3,2,5,62.4,3,16,5.3,0,1,0
3538,chrisweinke/2504686,"Weinke, Chris",2006,16,0,ATL,1,10 to 3,4,7,...,0,3,21,108.3,1,0,0.0,0,1,0
3539,chrisweinke/2504686,"Weinke, Chris",2001,2,0,ATL,0,16 to 24,27,41,...,0,2,6,85.0,1,5,5.0,1,1,0
3540,chrisweinke/2504686,"Weinke, Chris",2001,3,1,GB,0,7 to 28,18,30,...,1,2,15,71.5,3,5,1.7,0,2,0
3541,chrisweinke/2504686,"Weinke, Chris",2001,5,1,NO,0,25 to 27,21,39,...,1,1,12,74.3,3,2,0.7,0,2,2
3542,chrisweinke/2504686,"Weinke, Chris",2001,8,0,MIA,0,6 to 23,9,21,...,1,1,5,49.3,1,16,16.0,0,1,0
3543,chrisweinke/2504686,"Weinke, Chris",2001,12,0,NO,0,23 to 27,11,19,...,0,8,60,85.6,2,7,3.5,2,1,0
3544,chrisweinke/2504686,"Weinke, Chris",2001,15,1,STL,0,32 to 38,24,51,...,0,1,7,73.3,1,23,23.0,0,1,0
3545,chrisweinke/2504686,"Weinke, Chris",2001,16,1,ARI,0,7 to 30,36,63,...,1,0,0,63.1,5,19,3.8,0,1,0
3546,chrisweinke/2504686,"Weinke, Chris",2001,17,1,NE,0,6 to 38,15,36,...,3,2,15,18.8,1,0,0.0,0,1,1
3547,brockosweiler/2533436,"Osweiler, Brock",2016,6,1,IND,1,26 to 23,25,39,...,1,1,13,90.7,2,-4,-2.0,0,1,0
3548,brockosweiler/2533436,"Osweiler, Brock",2016,7,0,DEN,0,9 to 27,22,41,...,0,1,0,60.1,3,16,5.3,0,3,1
3549,brockosweiler/2533436,"Osweiler, Brock",2016,18,1,OAK,1,27 to 14,14,25,...,0,0,0,90.1,6,15,2.5,1,1,0
3550,brockosweiler/2533436,"Osweiler, Brock",2015,14,1,OAK,0,12 to 15,35,51,...,0,5,32,84.4,3,10,3.3,0,1,0
3551,brockosweiler/2533436,"Osweiler, Brock",2015,15,0,PIT,0,27 to 34,21,44,...,1,2,15,83.1,5,19,3.8,1,2,0

## Preparting Data Sets for Master Set

In [18]:
master_data = hof_data_with_id
master_data.drop('Pos', axis=1, inplace=True)
master_data.drop('Indct', axis=1, inplace=True)
master_data.drop('From', axis=1, inplace=True)
master_data.drop('To', axis=1, inplace=True)

In [19]:
master_data

,Rk,Player,First_Team_AP,Pro_Bowl,Num_Games,Pass_Cmp,Pass_Att,Pass_Yds,Pass_TD,Interceptions,Times_Sacked,Rushing_Att,Rushing_Yds,Rushing_Tds,Player_Id
0,19,Kurt Warner\WarnKu00,2,4,124,2666.0,4070.0,32344.0,208.0,128.0,260.0,173.0,286.0,3.0,kurtwarner/2503540
1,20,Brett Favre\FavrBr00,3,11,302,6300.0,10169.0,71838.0,508.0,336.0,525.0,602.0,1844.0,14.0,brettfavre/2500606
2,81,Troy Aikman\AikmTr00,0,6,165,2898.0,4715.0,32942.0,165.0,141.0,259.0,327.0,1016.0,9.0,troyaikman/2499369
3,87,Dan Marino\MariDa00,3,9,242,4967.0,8358.0,61361.0,420.0,252.0,270.0,301.0,87.0,9.0,danmarino/2501869
4,89,Steve Young\YounSt00,3,7,169,2667.0,4149.0,33124.0,232.0,107.0,358.0,722.0,4239.0,43.0,steveyoung/2503843
5,92,John Elway\ElwaJo00,0,9,234,4123.0,7250.0,51475.0,300.0,226.0,516.0,774.0,3407.0,33.0,johnelway/2500547
6,100,Jim Kelly\KellJi00,1,5,160,2874.0,4779.0,35467.0,237.0,175.0,323.0,304.0,1049.0,7.0,jimkelly/2501579\n5487
7,137,Dan Fouts\FoutDa00,2,6,181,3297.0,5604.0,43040.0,254.0,242.0,319.0,224.0,476.0,13.0,danfouts/2514293
8,162,Len Dawson\DawsLe00,2,7,211,2136.0,3741.0,28711.0,239.0,183.0,167.0,294.0,1293.0,9.0,lendawson/2512662
9,171,Fran Tarkenton\TarkFr00,1,9,246,3686.0,6467.0,47003.0,342.0,266.0,274.0,675.0,3674.0,32.0,frantarkenton/2527019
10,174,Joe Namath\NamaJo00,1,5,140,1886.0,3762.0,27663.0,173.0,220.0,109.0,71.0,140.0,7.0,joenamath/2521943
11,200,Johnny Unitas\UnitJo00,5,10,211,2830.0,5186.0,40239.0,290.0,253.0,74.0,450.0,1777.0,13.0,johnnyunitas/2527792